---
title: "CS102_IT2C_JUNTANILLA"
author: "Jose Roland Juntanilla"
output: html_document
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)
library(xml2)


```

FIRST PRODUCT MUSICAL INSTRUMENTS
```{r}
urllink <- "https://www.amazon.co.uk/s?k=instruments&rh=n%3A340837031&dc&ds=v1%3AnxfUJ3UllgrQDXHZjXo1VWBc0ID9B6QuK4S6bHxayXI&qid=1708177654&rnid=1642204031&ref=sr_nr_n_1"

itemdf <- data.frame()

session <- bow(urllink,user_agent = "For Educational Purposes")

    productscrape <- function(selector){
    scrape(session) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
itemname <- productscrape("span.a-text-normal")
itemname <- itemname[2:13]

itemprice <- productscrape("span.a-price")
itemprice <- itemprice[2:13]

itemrate <- productscrape("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate <- itemrate[2:13]

itemreview <- productscrape("span.a-size-base.s-underline-text")
itemreview <- itemreview[2:13]

firstitem <- rbind(itemdf, data.frame(
                      Name = itemname,
                      Price = itemprice,
                      Ratings = itemrate,
                      TotalReview = itemreview))



```

```{r}
urllink2<-"https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=2&qid=1708177676&rnid=1642204031&ref=sr_pg_2"

itemdf2 <- data.frame()

session2 <- bow(urllink2,user_agent = "For Educational Purposes")




 productscrape2 <- function(selector){
    scrape(session2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname2 <- productscrape2("span.a-text-normal")
itemname2 <- itemname2[2:12]

itemprice2 <- productscrape2("span.a-price")
itemprice2 <- itemprice2[2:12]

itemrate2 <- productscrape2("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate2 <- itemrate2[2:12]

itemreview2 <- productscrape2("span.a-size-base.s-underline-text")
itemreview2 <- itemreview2[2:12]

firstitem2 <- rbind(itemdf2, data.frame(
                      Name = itemname2,
                      Price = itemprice2,
                      Ratings = itemrate2,
                      TotalReview = itemreview2))




```


```{r}
urllink3 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=3&qid=1708177997&rnid=1642204031&ref=sr_pg_3"

itemdf3 <- data.frame()

session3 <- bow(urllink3,user_agent = "For Educational Purposes")




 productscrape3 <- function(selector){
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname3 <- productscrape3("span.a-text-normal")
itemname3 <- itemname3[2:11]

itemprice3 <- productscrape3("span.a-price")
itemprice3 <- itemprice3[2:11]

itemrate3 <- productscrape3("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate3 <- itemrate3[2:11]

itemreview3 <- productscrape3("span.a-size-base.s-underline-text")
itemreview3 <- itemreview3[2:11]

firstitem3 <- rbind(itemdf3, data.frame(
                      Name = itemname3,
                      Price = itemprice3,
                      Ratings = itemrate3,
                      TotalReview = itemreview3))



```

```{r}
urllink4 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=4&qid=1708178154&rnid=1642204031&ref=sr_pg_4"

itemdf4 <- data.frame()

session4 <- bow(urllink4,user_agent = "For Educational Purposes")




 productscrape4 <- function(selector){
    scrape(session4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname4 <- productscrape4("span.a-text-normal")
itemname4 <- itemname4[2:11]

itemprice4 <- productscrape4("span.a-price")
itemprice4 <- itemprice4[2:11]

itemrate4 <- productscrape4("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate4 <- itemrate4[2:11]

itemreview4 <- productscrape4("span.a-size-base.s-underline-text")
itemreview4 <- itemreview4[2:11]

firstitem4 <- rbind(itemdf4, data.frame(
                      Name = itemname4,
                      Price = itemprice4,
                      Ratings = itemrate4,
                      TotalReview = itemreview4))


```

```{r}
urllink5 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=5&qid=1708179027&rnid=1642204031&ref=sr_pg_5"

itemdf5 <- data.frame()

session5 <- bow(urllink5,user_agent = "For Educational Purposes")




 productscrape5 <- function(selector){
    scrape(session5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname5 <- productscrape5("span.a-text-normal")
itemname5 <- itemname5[2:10]

itemprice5 <- productscrape5("span.a-price")
itemprice5 <- itemprice5[2:10]

itemrate5 <- productscrape5("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate5 <- itemrate5[2:10]

itemreview5 <- productscrape5("span.a-size-base.s-underline-text")
itemreview5 <- itemreview5[2:10]

firstitem5 <- rbind(itemdf5, data.frame(
                      Name = itemname5,
                      Price = itemprice5,
                      Ratings = itemrate5,
                      TotalReview = itemreview5))


```

```{r}
urllink6 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=6&qid=1708179031&rnid=1642204031&ref=sr_pg_6"

itemdf6 <- data.frame()

session6 <- bow(urllink6,user_agent = "For Educational Purposes")




 productscrape6 <- function(selector){
    scrape(session6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname6 <- productscrape6("span.a-text-normal")
itemname6 <- itemname6[2:9]

itemprice6 <- productscrape6("span.a-price")
itemprice6 <- itemprice6[2:9]

itemrate6 <- productscrape6("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate6 <- itemrate6[2:9]

itemreview6 <- productscrape6("span.a-size-base.s-underline-text")
itemreview6 <- itemreview6[2:9]

firstitem6 <- rbind(itemdf6, data.frame(
                      Name = itemname6,
                      Price = itemprice6,
                      Ratings = itemrate6,
                      TotalReview = itemreview6))


```

```{r}
urllink7 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=7&qid=1708179293&rnid=1642204031&ref=sr_pg_7"

itemdf7 <- data.frame()

session7 <- bow(urllink7,user_agent = "For Educational Purposes")




 productscrape7 <- function(selector){
    scrape(session7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname7 <- productscrape7("span.a-text-normal")
itemname7 <- itemname7[2:11]

itemprice7 <- productscrape7("span.a-price")
itemprice7 <- itemprice7[2:11]

itemrate7 <- productscrape7("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate7 <- itemrate7[2:11]

itemreview7 <- productscrape7("span.a-size-base.s-underline-text")
itemreview7 <- itemreview7[2:11]

firstitem7 <- rbind(itemdf7, data.frame(
                      Name = itemname7,
                      Price = itemprice7,
                      Ratings = itemrate7,
                      TotalReview = itemreview7))


```

```{r}
urllink8 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=9&qid=1708261405&rnid=1642204031&ref=sr_pg_9"

itemdf8 <- data.frame()

session8 <- bow(urllink8,user_agent = "For Educational Purposes")




 productscrape8 <- function(selector){
    scrape(session8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname8 <- productscrape8("span.a-text-normal")
itemname8 <- itemname8[2:16]

itemprice8 <- productscrape8("span.a-price")
itemprice8 <- itemprice8[2:16]

itemrate8 <- productscrape8("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate8 <- itemrate8[2:16]

itemreview8 <- productscrape8("span.a-size-base.s-underline-text")
itemreview8 <- itemreview8[2:16]

firstitem8 <- rbind(itemdf8, data.frame(
                      Name = itemname8,
                      Price = itemprice8,
                      Ratings = itemrate8,
                      TotalReview = itemreview8))


```
```{r}
urllink9 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=10&qid=1708261452&rnid=1642204031&ref=sr_pg_10"

itemdf9 <- data.frame()

session9 <- bow(urllink9,user_agent = "For Educational Purposes")




 productscrape9 <- function(selector){
    scrape(session9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname9 <- productscrape9("span.a-text-normal")
itemname9 <- itemname9[2:10]

itemprice9 <- productscrape9("span.a-price")
itemprice9 <- itemprice9[2:10]

itemrate9 <- productscrape9("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate9 <- itemrate9[2:10]

itemreview9 <- productscrape9("span.a-size-base.s-underline-text")
itemreview9 <- itemreview9[2:10]

firstitem9 <- rbind(itemdf9, data.frame(
                      Name = itemname9,
                      Price = itemprice9,
                      Ratings = itemrate9,
                      TotalReview = itemreview9))


```

```{r}
urllink10 <- "https://www.amazon.co.uk/s?k=instruments&i=mi&rh=n%3A340837031&dc&page=8&qid=1708261397&rnid=1642204031&ref=sr_pg_8"

itemdf10 <- data.frame()

session10 <- bow(urllink10,user_agent = "For Educational Purposes")




 productscrape10 <- function(selector){
    scrape(session10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
itemname10 <- productscrape10("span.a-text-normal")
itemname10 <- itemname10[2:7]

itemprice10 <- productscrape10("span.a-price")
itemprice10 <- itemprice10[2:7]

itemrate10 <- productscrape10("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
itemrate10 <- itemrate10[2:7]

itemreview10 <- productscrape10("span.a-size-base.s-underline-text")
itemreview10 <- itemreview10[2:7]

firstitem10 <- rbind(itemdf10, data.frame(
                      Name = itemname10,
                      Price = itemprice10,
                      Ratings = itemrate10,
                      TotalReview = itemreview10))


```
```{r}
first_product_combine <- rbind(firstitem,firstitem2,firstitem3,firstitem4,firstitem5,firstitem6,firstitem7,firstitem8,firstitem9,firstitem10)

```


SECOND PRODUCT TOYS
```{r}

linkurl <- "https://www.amazon.co.uk/s?bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&qid=1708180905&rnid=391457011&ref=lp"
  
proddf <- data.frame()

resp <- bow(linkurl,user_agent = "For Educational Purposes")




 scrapeprod <- function(selector){
    scrape(resp) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname <- scrapeprod("span.a-text-normal")
productname <- productname[2:8]

productprice <- scrapeprod("span.a-price")
productprice <- productprice[2:8]

productrate <- scrapeprod("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate <- productrate[2:8]

productrev <- scrapeprod("span.a-size-base.s-underline-text")
productrev <- productrev[2:8]

seconditem <- rbind(proddf, data.frame(
                      Name = productname,
                      Price = productprice,
                      Ratings = productrate,
                      TotalReview = productrev))


```

```{r}

linkurl2 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=2&qid=1708258274&rnid=391457011&ref=sr_pg_2"
  
proddf2 <- data.frame()

resp2 <- bow(linkurl2,user_agent = "For Educational Purposes")




 scrapeprod2 <- function(selector){
    scrape(resp2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname2 <- scrapeprod2("span.a-text-normal")
productname2 <- productname2[2:9]

productprice2 <- scrapeprod2("span.a-price")
productprice2 <- productprice2[2:9]

productrate2 <- scrapeprod2("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate2 <- productrate2[2:9]

productrev2 <- scrapeprod2("span.a-size-base.s-underline-text")
productrev2 <- productrev2[2:9]

seconditem2 <- rbind(proddf2, data.frame(
                      Name = productname2,
                      Price = productprice2,
                      Ratings = productrate2,
                      TotalReview = productrev2))


```

```{r}

linkurl3 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=3&qid=1708258434&rnid=391457011&ref=sr_pg_3"
  
proddf3 <- data.frame()

resp3 <- bow(linkurl3,user_agent = "For Educational Purposes")




 scrapeprod3 <- function(selector){
    scrape(resp3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname3 <- scrapeprod3("span.a-text-normal")
productname3 <- productname3[2:13]
productprice3 <- scrapeprod3("span.a-price")
productprice3 <- productprice3[2:13]

productrate3 <- scrapeprod3("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate3 <- productrate3[2:13]

productrev3 <- scrapeprod3("span.a-size-base.s-underline-text")
productrev3 <- productrev3[2:13]

seconditem3 <- rbind(proddf3, data.frame(
                      Name = productname3,
                      Price = productprice3,
                      Ratings = productrate3,
                      TotalReview = productrev3))


```

```{r}

linkurl4 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=4&qid=1708258749&rnid=391457011&ref=sr_pg_4"
  
proddf4 <- data.frame()

resp4 <- bow(linkurl4,user_agent = "For Educational Purposes")




 scrapeprod4 <- function(selector){
    scrape(resp4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname4 <- scrapeprod4("span.a-text-normal")
productname4 <- productname4[2:13]
productprice4 <- scrapeprod4("span.a-price")
productprice4 <- productprice4[2:13]

productrate4 <- scrapeprod4("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate4 <- productrate4[2:13]

productrev4 <- scrapeprod4("span.a-size-base.s-underline-text")
productrev4 <- productrev4[2:13]

seconditem4 <- rbind(proddf4, data.frame(
                      Name = productname4,
                      Price = productprice4,
                      Ratings = productrate4,
                      TotalReview = productrev4))


```

```{r}

linkurl5 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=6&qid=1708259493&rnid=391457011&ref=sr_pg_6"
  
proddf5 <- data.frame()

resp5 <- bow(linkurl5,user_agent = "For Educational Purposes")




 scrapeprod5 <- function(selector){
    scrape(resp5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname5 <- scrapeprod5("span.a-text-normal")
productname5 <- productname5[2:8]
productprice5 <- scrapeprod5("span.a-price")
productprice5 <- productprice5[2:8]

productrate5 <- scrapeprod5("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate5 <- productrate5[2:8]

productrev5 <- scrapeprod5("span.a-size-base.s-underline-text")
productrev5 <- productrev5[2:8]

seconditem5 <- rbind(proddf5, data.frame(
                      Name = productname5,
                      Price = productprice5,
                      Ratings = productrate5,
                      TotalReview = productrev5))


```

```{r}

linkurl6 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=7&qid=1708259561&rnid=391457011&ref=sr_pg_7"
  
proddf6 <- data.frame()

resp6 <- bow(linkurl6,user_agent = "For Educational Purposes")




 scrapeprod6 <- function(selector){
    scrape(resp6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname6 <- scrapeprod6("span.a-text-normal")
productname6 <- productname6[2:8]
productprice6 <- scrapeprod6("span.a-price")
productprice6 <- productprice6[2:8]

productrate6 <- scrapeprod6("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate6 <- productrate6[2:8]

productrev6 <- scrapeprod6("span.a-size-base.s-underline-text")
productrev6 <- productrev6[2:8]

seconditem6 <- rbind(proddf6, data.frame(
                      Name = productname6,
                      Price = productprice6,
                      Ratings = productrate6,
                      TotalReview = productrev6))


```

```{r}

linkurl7 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=8&qid=1708259643&rnid=391457011&ref=sr_pg_8"
  
proddf7 <- data.frame()

resp7 <- bow(linkurl7,user_agent = "For Educational Purposes")




 scrapeprod7 <- function(selector){
    scrape(resp7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname7 <- scrapeprod7("span.a-text-normal")
productname7 <- productname7[2:12]
productprice7 <- scrapeprod7("span.a-price")
productprice7 <- productprice7[2:12]

productrate7 <- scrapeprod7("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate7 <- productrate7[2:12]

productrev7 <- scrapeprod7("span.a-size-base.s-underline-text")
productrev7 <- productrev7[2:12]

seconditem7 <- rbind(proddf7, data.frame(
                      Name = productname7,
                      Price = productprice7,
                      Ratings = productrate7,
                      TotalReview = productrev7))


```
```{r}

linkurl7 <- "https://www.amazon.co.uk/s?i=toys&bbn=364272031&rh=n%3A364272031%2Cp_n_age_range%3A4220475031&dc&page=8&qid=1708259643&rnid=391457011&ref=sr_pg_8"
  
proddf7 <- data.frame()

resp7 <- bow(linkurl7,user_agent = "For Educational Purposes")




 scrapeprod7 <- function(selector){
    scrape(resp7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname7 <- scrapeprod7("span.a-text-normal")
productname7 <- productname7[2:11]
productprice7 <- scrapeprod7("span.a-price")
productprice7 <- productprice7[2:11]

productrate7 <- scrapeprod7("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate7 <- productrate7[2:11]

productrev7 <- scrapeprod7("span.a-size-base.s-underline-text")
productrev7 <- productrev7[2:11]

seconditem7 <- rbind(proddf7, data.frame(
                      Name = productname7,
                      Price = productprice7,
                      Ratings = productrate7,
                      TotalReview = productrev7))


```

```{r}

linkurl8 <- "https://www.amazon.co.uk/s?rh=n%3A364272031%2Cp_36%3A146171031&content-id=amzn1.sym.d31debd2-935f-4aa7-97e3-6956a4bc403f&pd_rd_r=08fd0b2c-2176-420c-870d-4fec822ff743&pd_rd_w=vENDV&pd_rd_wg=Z21jQ&pf_rd_p=d31debd2-935f-4aa7-97e3-6956a4bc403f&pf_rd_r=B85BPESXR2W2P6D442S3&ref=Oct_d_oup_S"
  
proddf8 <- data.frame()

resp8 <- bow(linkurl8,user_agent = "For Educational Purposes")




 scrapeprod8 <- function(selector){
    scrape(resp8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname8 <- scrapeprod8("span.a-text-normal")
productname8 <- productname8[2:19]
productprice8 <- scrapeprod8("span.a-price")
productprice8 <- productprice8[2:19]

productrate8 <- scrapeprod8("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate8 <- productrate8[2:19]

productrev8 <- scrapeprod8("span.a-size-base.s-underline-text")
productrev8 <- productrev8[2:19]

seconditem8 <- rbind(proddf8, data.frame(
                      Name = productname8,
                      Price = productprice8,
                      Ratings = productrate8,
                      TotalReview = productrev8))


```

```{r}

linkurl9 <- "https://www.amazon.co.uk/s?i=toys&rh=n%3A364272031%2Cp_36%3A146171031&page=2&content-id=amzn1.sym.d31debd2-935f-4aa7-97e3-6956a4bc403f&pd_rd_r=08fd0b2c-2176-420c-870d-4fec822ff743&pd_rd_w=vENDV&pd_rd_wg=Z21jQ&pf_rd_p=d31debd2-935f-4aa7-97e3-6956a4bc403f&pf_rd_r=B85BPESXR2W2P6D442S3&qid=1708260177&ref=sr_pg_2"
  
proddf9 <- data.frame()

resp9 <- bow(linkurl9,user_agent = "For Educational Purposes")




 scrapeprod9 <- function(selector){
    scrape(resp9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname9 <- scrapeprod9("span.a-text-normal")
productname9 <- productname9[2:11]
productprice9 <- scrapeprod9("span.a-price")
productprice9 <- productprice9[2:11]

productrate9 <- scrapeprod9("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate9 <- productrate7[2:11]

productrev9 <- scrapeprod9("span.a-size-base.s-underline-text")
productrev9 <- productrev9[2:11]

seconditem9 <- rbind(proddf9, data.frame(
                      Name = productname9,
                      Price = productprice9,
                      Ratings = productrate9,
                      TotalReview = productrev9))


```

```{r}

linkurl10 <- "https://www.amazon.co.uk/s?i=toys&rh=n%3A364272031%2Cp_36%3A146171031&page=3&content-id=amzn1.sym.d31debd2-935f-4aa7-97e3-6956a4bc403f&pd_rd_r=08fd0b2c-2176-420c-870d-4fec822ff743&pd_rd_w=vENDV&pd_rd_wg=Z21jQ&pf_rd_p=d31debd2-935f-4aa7-97e3-6956a4bc403f&pf_rd_r=B85BPESXR2W2P6D442S3&qid=1708260306&ref=sr_pg_3"
  
proddf10 <- data.frame()

resp10 <- bow(linkurl10,user_agent = "For Educational Purposes")




 scrapeprod10 <- function(selector){
    scrape(resp10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
}
   
   
productname10 <- scrapeprod10("span.a-text-normal")
productname10 <- productname10[2:10]
productprice10 <- scrapeprod10("span.a-price")
productprice10 <- productprice10[2:10]

productrate10 <- scrapeprod10("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom")
productrate10 <- productrate10[2:10]

productrev10 <- scrapeprod10("span.a-size-base.s-underline-text")
productrev10 <- productrev10[2:10]

seconditem10 <- rbind(proddf10, data.frame(
                      Name = productname10,
                      Price = productprice10,
                      Ratings = productrate10,
                      TotalReview = productrev10))


```

```{r}
second_product_combine <- rbind(seconditem,seconditem2,seconditem3,seconditem4,seconditem5,seconditem6,seconditem7,seconditem8,seconditem9,seconditem10)

```

Movies With Reviews
```{r}
movieurl <- "https://www.imdb.com/title/tt23849204/reviews/?ref_=tt_ov_rt"

moviedf = data.frame()


moviesession <- bow(movieurl,user_agent = "For Educational Purposes")




 scrapemov <- function(selector){
    scrape(moviesession) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat <- rep("Movie", 25)

  movname <- scrapemov("a.subnav_heading")
  movname <- rep(movname, 25)
  movname <- movname[1:25]
  
  nameofreviewer <- scrapemov("span.display-name-link")
  nameofreviewer <- nameofreviewer[1:25]
  
  movierev <- scrapemov("div.text.show-more__control")
  movierev <- movierev[1:25]
  
  moviedate <- scrapemov("span.review-date")
  moviedate <- moviedate[1:25]
  
  movierate <- scrapemov("span.rating-other-user-rating")
  movierate <- movierate[1:25]

  
  movie1 <- rbind(moviedf, data.frame(
                          Category = moviecat,
                          Name = movname,
                          Reviewers_Name = nameofreviewer,
                          Reviews = movierev,
                          Review_Date = moviedate,
                          Rating = movierate))

```

```{r}
movieurl2 <- "https://www.imdb.com/title/tt0259534/reviews/?ref_=tt_ov_rt"

moviedf2 = data.frame()


moviesession2 <- bow(movieurl2,user_agent = "For Educational Purposes")




 scrapemov2 <- function(selector){
    scrape(moviesession2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat2 <- rep("Movie", 25)

  movname2 <- scrapemov2("a.subnav_heading")
  movname2 <- rep(movname2, 25)
  movname2 <- movname2[1:25]
  
  nameofreviewer2 <- scrapemov2("span.display-name-link")
  nameofreviewer2 <- nameofreviewer2[1:25]
  
  movierev2 <- scrapemov2("div.text.show-more__control")
  movierev2 <- movierev2[1:25]
  
  moviedate2 <- scrapemov2("span.review-date")
  moviedate2 <- moviedate2[1:25]
  
  movierate2 <- scrapemov2("span.rating-other-user-rating")
  movierate2 <- movierate2[1:25]

  
  movie2 <- rbind(moviedf2, data.frame(
                          Category = moviecat2,
                          Name = movname2,
                          Reviewers_Name = nameofreviewer2,
                          Reviews = movierev2,
                          Review_Date = moviedate2,
                          Rating = movierate2))

```

```{r}
movieurl3 <- "https://www.imdb.com/title/tt0093603/reviews/?ref_=tt_ov_rt"

moviedf3 = data.frame()


moviesession3 <- bow(movieurl3,user_agent = "For Educational Purposes")




 scrapemov3 <- function(selector){
    scrape(moviesession3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat3 <- rep("Movie", 25)

  movname3 <- scrapemov3("a.subnav_heading")
  movname3 <- rep(movname3, 25)
  movname3 <- movname3[1:25]
  
  nameofreviewer3 <- scrapemov3("span.display-name-link")
  nameofreviewer3 <- nameofreviewer3[1:25]
  
  movierev3 <- scrapemov3("div.text.show-more__control")
  movierev3 <- movierev3[1:25]
  
  moviedate3 <- scrapemov3("span.review-date")
  moviedate3 <- moviedate3[1:25]
  
  movierate3 <- scrapemov3("span.rating-other-user-rating")
  movierate3 <- movierate3[1:25]

  
  movie3 <- rbind(moviedf3, data.frame(
                          Category = moviecat3,
                          Name = movname3,
                          Reviewers_Name = nameofreviewer3,
                          Reviews = movierev3,
                          Review_Date = moviedate3,
                          Rating = movierate3))

```

```{r}
movieurl4 <- "https://www.imdb.com/title/tt7466810/reviews/?ref_=tt_ov_rt"

moviedf4 = data.frame()


moviesession4 <- bow(movieurl4,user_agent = "For Educational Purposes")




 scrapemov4 <- function(selector){
    scrape(moviesession4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat4 <- rep("Movie", 25)

  movname4 <- scrapemov4("a.subnav_heading")
  movname4 <- rep(movname4, 25)
  movname4 <- movname4[1:25]
  
  nameofreviewer4 <- scrapemov4("span.display-name-link")
  nameofreviewer4 <- nameofreviewer4[1:25]
  
  movierev4 <- scrapemov4("div.text.show-more__control")
  movierev4 <- movierev4[1:25]
  
  moviedate4 <- scrapemov4("span.review-date")
  moviedate4 <- moviedate4[1:25]
  
  movierate4 <- scrapemov4("span.rating-other-user-rating")
  movierate4 <- movierate4[1:25]

  
  movie4 <- rbind(moviedf4, data.frame(
                          Category = moviecat4,
                          Name = movname4,
                          Reviewers_Name = nameofreviewer4,
                          Reviews = movierev4,
                          Review_Date = moviedate4,
                          Rating = movierate4))

```

```{r}
movieurl5 <- "https://www.imdb.com/title/tt0079221/reviews/?ref_=tt_ov_rt"

moviedf5 = data.frame()


moviesession5 <- bow(movieurl5,user_agent = "For Educational Purposes")




 scrapemov5 <- function(selector){
    scrape(moviesession5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat5 <- rep("Movie", 25)

  movname5 <- scrapemov5("a.subnav_heading")
  movname5 <- rep(movname5, 25)
  movname5 <- movname5[1:25]
  
  nameofreviewer5 <- scrapemov5("span.display-name-link")
  nameofreviewer5 <- nameofreviewer5[1:25]
  
  movierev5 <- scrapemov5("div.text.show-more__control")
  movierev5 <- movierev5[1:25]
  
  moviedate5 <- scrapemov5("span.review-date")
  moviedate5 <- moviedate5[1:25]
  
  movierate5 <- scrapemov5("span.rating-other-user-rating")
  movierate5 <- movierate5[1:25]

  
  movie5 <- rbind(moviedf5, data.frame(
                          Category = moviecat5,
                          Name = movname5,
                          Reviewers_Name = nameofreviewer5,
                          Reviews = movierev5,
                          Review_Date = moviedate5,
                          Rating = movierate5))

```

```{r}
movieurl6 <- "https://www.imdb.com/title/tt9263550/reviews/?ref_=tt_ov_rt"

moviedf6 = data.frame()


moviesession6 <- bow(movieurl6,user_agent = "For Educational Purposes")




 scrapemov6 <- function(selector){
    scrape(moviesession6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat6 <- rep("Movie", 25)

  movname6 <- scrapemov6("a.subnav_heading")
  movname6 <- rep(movname6, 25)
  movname6 <- movname6[1:25]
  
  nameofreviewer6 <- scrapemov6("span.display-name-link")
  nameofreviewer6 <- nameofreviewer6[1:25]
  
  movierev6 <- scrapemov6("div.text.show-more__control")
  movierev6 <- movierev6[1:25]
  
  moviedate6 <- scrapemov6("span.review-date")
  moviedate6 <- moviedate6[1:25]
  
  movierate6 <- scrapemov6("span.rating-other-user-rating")
  movierate6 <- movierate6[1:25]

  
  movie6 <- rbind(moviedf6, data.frame(
                          Category = moviecat6,
                          Name = movname6,
                          Reviewers_Name = nameofreviewer6,
                          Reviews = movierev6,
                          Review_Date = moviedate6,
                          Rating = movierate6))

```

```{r}
movieurl7 <- "https://www.imdb.com/title/tt0367495/reviews/?ref_=tt_ov_rt"

moviedf7 = data.frame()


moviesession7 <- bow(movieurl7,user_agent = "For Educational Purposes")




 scrapemov7 <- function(selector){
    scrape(moviesession7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat7 <- rep("Movie", 25)

  movname7 <- scrapemov7("a.subnav_heading")
  movname7 <- rep(movname7, 25)
  movname7 <- movname7[1:25]
  
  nameofreviewer7 <- scrapemov7("span.display-name-link")
  nameofreviewer7 <- nameofreviewer7[1:25]
  
  movierev7 <- scrapemov7("div.text.show-more__control")
  movierev7 <- movierev7[1:25]
  
  moviedate7 <- scrapemov7("span.review-date")
  moviedate7 <- moviedate7[1:25]
  
  movierate7 <- scrapemov7("span.rating-other-user-rating")
  movierate7 <- movierate7[1:25]

  
  movie7 <- rbind(moviedf7, data.frame(
                          Category = moviecat7,
                          Name = movname7,
                          Reviewers_Name = nameofreviewer7,
                          Reviews = movierev7,
                          Review_Date = moviedate7,
                          Rating = movierate7))

```

```{r}
movieurl8 <- "https://www.imdb.com/title/tt8176054/reviews/?ref_=tt_ov_rt"

moviedf8 = data.frame()


moviesession8 <- bow(movieurl8,user_agent = "For Educational Purposes")




 scrapemov8 <- function(selector){
    scrape(moviesession8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat8 <- rep("Movie", 25)

  movname8 <- scrapemov8("a.subnav_heading")
  movname8 <- rep(movname8, 25)
  movname8 <- movname8[1:25]
  
  nameofreviewer8 <- scrapemov8("span.display-name-link")
  nameofreviewer8 <- nameofreviewer8[1:25]
  
  movierev8 <- scrapemov8("div.text.show-more__control")
  movierev8 <- movierev8[1:25]
  
  moviedate8 <- scrapemov8("span.review-date")
  moviedate8 <- moviedate8[1:25]
  
  movierate8 <- scrapemov8("span.rating-other-user-rating")
  movierate8 <- movierate8[1:25]

  
  movie8 <- rbind(moviedf8, data.frame(
                          Category = moviecat8,
                          Name = movname8,
                          Reviewers_Name = nameofreviewer8,
                          Reviews = movierev8,
                          Review_Date = moviedate8,
                          Rating = movierate8))

```

```{r}
movieurl9 <- "https://www.imdb.com/title/tt0214915/reviews/?ref_=tt_ov_rt"

moviedf9 = data.frame()


moviesession9 <- bow(movieurl9,user_agent = "For Educational Purposes")




 scrapemov9 <- function(selector){
    scrape(moviesession9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat9 <- rep("Movie", 25)

  movname9 <- scrapemov9("a.subnav_heading")
  movname9 <- rep(movname9, 25)
  movname9 <- movname9[1:25]
  
  nameofreviewer9 <- scrapemov9("span.display-name-link")
  nameofreviewer9 <- nameofreviewer9[1:25]
  
  movierev9 <- scrapemov9("div.text.show-more__control")
  movierev9 <- movierev9[1:25]
  
  moviedate9 <- scrapemov9("span.review-date")
  moviedate9 <- moviedate9[1:25]
  
  movierate9 <- scrapemov9("span.rating-other-user-rating")
  movierate9 <- movierate9[1:25]

  
  movie9 <- rbind(moviedf9, data.frame(
                          Category = moviecat9,
                          Name = movname9,
                          Reviewers_Name = nameofreviewer9,
                          Reviews = movierev9,
                          Review_Date = moviedate9,
                          Rating = movierate9))

```

```{r}
movieurl10 <- "https://www.imdb.com/title/tt1187043/reviews/?ref_=tt_ov_rt"

moviedf10 = data.frame()


moviesession10 <- bow(movieurl10,user_agent = "For Educational Purposes")




 scrapemov10 <- function(selector){
    scrape(moviesession10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
   
 }
 
  moviecat10 <- rep("Movie", 25)

  movname10 <- scrapemov10("a.subnav_heading")
  movname10 <- rep(movname10, 25)
  movname10 <- movname10[1:25]
  
  nameofreviewer10 <- scrapemov10("span.display-name-link")
  nameofreviewer10 <- nameofreviewer10[1:25]
  
  movierev10 <- scrapemov10("div.text.show-more__control")
  movierev10 <- movierev10[1:25]
  
  moviedate10 <- scrapemov10("span.review-date")
  moviedate10 <- moviedate10[1:25]
  
  movierate10 <- scrapemov10("span.rating-other-user-rating")
  movierate10 <- movierate10[1:25]

  
  movie10 <- rbind(moviedf10, data.frame(
                          Category = moviecat10,
                          Name = movname10,
                          Reviewers_Name = nameofreviewer10,
                          Reviews = movierev10,
                          Review_Date = moviedate10,
                          Rating = movierate10))

```

```{r}
Combined_25_movies <- rbind(movie1,movie2,movie3,movie4,movie5,movie6,movie7,movie8,movie9,movie10)
```